config_path: '$DESCODE/SIMS/AURA/simulations/config/DES_BS20_age_Rv_step_3Gyr_age_x1_beta_1.14.yaml'
#config_path: /Users/ishfahanirusyda/DES/SIMS/AURA/simulations/config/DES_BS20_age_Rv_step_3Gyr_age_x1_beta_1.14.yaml
#config_path: '/Users/ishfahanirusyda/master_thesis/des_sn_hosts/simulations/config/DES_BS20_age_Rv_step_3Gyr_age_x1_beta_1.14.yaml'
Rv_lo:
    lo: 1.5
    hi: 2.25
    step: 0.25
Rv_hi:
    lo: 1.5
    hi: 2.25
    step: 0.25
age_step:
    lo: 0.0
    hi: 0.25
    step: 0.05
save:
    dir: 'age_step_Rv_lo_hicut_test_hostlib_nonmpi'

n_samples: 1000
