config_path: '$DESCODE/SIMS/AURA/simulations/config/BS21_massstep.yaml'

Rv_lo:
    lo: 1.50
    hi: 1.75
    step: 0.25
Rv_hi:
    lo: 3.00
    hi: 3.25
    step: 0.25
age_step:
    lo: 0.0
    hi: 0.05
    step: 0.05
save:
    dir: final/BS21_massstep

n_samples: 200000
