config_path: '/priv/debass/software/DES/SIMS/AURA/simulations/config/W21_intrinmass.yaml'
Rv_lo:
    lo: 1.5
    hi: 1.75
    step: 0.25
Rv_hi:
    lo: 2.75
    hi: 3.00
    step: 0.25
age_step:
    lo: 0.0
    hi: 0.05
    step: 0.05
save:
    dir: final_model_v1/fixed_with_neb/mass4

n_samples: 300000
