config_path: '/priv/debass/software/DES/SIMS/AURA/simulations/config/baseline_model.yaml'
Rv_lo:
    lo: 2.75
    hi: 3.00
    step: 0.25
Rv_hi:
    lo: 2.75
    hi: 3.00
    step: 0.25
age_step:
    lo: 0.0
    hi: 0.05
    step: 0.05
save:
    dir: 'final_model_v1/fixed_with_neb/av0-1.5'

n_samples: 300000
