#modify te=he value of mass step in config_path
config_path: '/priv/debass/software/DES/SIMS/AURA/simulations/config/BS21_intrinage.yaml'
Rv_lo:
    lo: 1.50
    hi: 1.75
    step: 0.25
Rv_hi:
    lo: 3.00
    hi: 3.25
    step: 0.25
age_step:
    lo: 0.10
    hi: 0.015
    step: 0.05
save:
    dir: final_model_v1/fixed_with_neb/ur2

n_samples: 300000
