config_path: '/priv/debass/software/DES/SIMS/AURA/simulations/config/W21_agestep.yaml'
Rv_lo:
    lo: 1.75
    hi: 2.00
    step: 0.25
Rv_hi:
    lo: 2.50
    hi: 2.75
    step: 0.25
age_step:
    lo: 0.15
    hi: 0.20
    step: 0.05
save:
    dir: final/W21_agestep

n_samples: 200000
